python train.py --device 1 -c configs/vae_mnist_L6.json
python train.py --device 1 -c configs/vae_mnist_L8.json
python train.py --device 1 -c configs/vae_mnist_L10.json
python train.py --device 1 -c configs/vae_mnist_L12.json
python train.py --device 1 -c configs/vae_mnist_L14.json
python train.py --device 1 -c configs/vae_mnist_L16.json
python train.py --device 1 -c configs/vae_mnist_L20.json
python train.py --device 1 -c configs/vae_mnist_L24.json
python train.py --device 1 -c configs/vae_mnist_L28.json
python train.py --device 1 -c configs/vae_mnist_L32.json

python train.py --device 1 -c configs/vae_mnist_rotate/vae_mnist_L6_rotate.json
python train.py --device 1 -c configs/vae_mnist_rotate/vae_mnist_L8_rotate.json
python train.py --device 1 -c configs/vae_mnist_rotate/vae_mnist_L10_rotate.json
python train.py --device 1 -c configs/vae_mnist_rotate/vae_mnist_L12_rotate.json
python train.py --device 1 -c configs/vae_mnist_rotate/vae_mnist_L14_rotate.json
python train.py --device 1 -c configs/vae_mnist_rotate/vae_mnist_L16_rotate.json
python train.py --device 1 -c configs/vae_mnist_rotate/vae_mnist_L20_rotate.json
python train.py --device 1 -c configs/vae_mnist_rotate/vae_mnist_L24_rotate.json
python train.py --device 1 -c configs/vae_mnist_rotate/vae_mnist_L28_rotate.json
python train.py --device 1 -c configs/vae_mnist_rotate/vae_mnist_L32_rotate.json